// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:expense/data/data/hive/hive_adapters.dart';
import 'package:hive_ce/hive_ce.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseDataAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExpenseDataAdapter());
    registerAdapter(TransactionTypeAdapter());
    registerAdapter(UserDataAdapter());
  }
}
